name: Android Release Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Create keystore file
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/travira-release-key.jks


      - name: Create keystore properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/keystore.properties
          echo "storeFile=../travira-release-key.jks" >> android/keystore.properties


      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease


      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Travira-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
